// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTMoxTTMooG0YMmZ0O4K4VD5UcbnYOJLo',
    appId: '1:1062076145636:web:9d7893d53314fde041b1f1',
    messagingSenderId: '1062076145636',
    projectId: 'shary-7be74',
    authDomain: 'shary-7be74.firebaseapp.com',
    storageBucket: 'shary-7be74.firebasestorage.app',
    measurementId: 'G-39LX1HZ6HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB51gXewTJiP2RsMBGUFMt9ng-gVu_iO0U',
    appId: '1:1062076145636:android:ca02db1e395e6bdd41b1f1',
    messagingSenderId: '1062076145636',
    projectId: 'shary-7be74',
    storageBucket: 'shary-7be74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_eNA26-XLARAKE-qKeD5VUlbusdArrNw',
    appId: '1:1062076145636:ios:bf6ade86b993a9df41b1f1',
    messagingSenderId: '1062076145636',
    projectId: 'shary-7be74',
    storageBucket: 'shary-7be74.firebasestorage.app',
    iosBundleId: 'com.example.shary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_eNA26-XLARAKE-qKeD5VUlbusdArrNw',
    appId: '1:1062076145636:ios:bf6ade86b993a9df41b1f1',
    messagingSenderId: '1062076145636',
    projectId: 'shary-7be74',
    storageBucket: 'shary-7be74.firebasestorage.app',
    iosBundleId: 'com.example.shary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTMoxTTMooG0YMmZ0O4K4VD5UcbnYOJLo',
    appId: '1:1062076145636:web:a538a623cd7ab7d041b1f1',
    messagingSenderId: '1062076145636',
    projectId: 'shary-7be74',
    authDomain: 'shary-7be74.firebaseapp.com',
    storageBucket: 'shary-7be74.firebasestorage.app',
    measurementId: 'G-H6H2CCTYYZ',
  );
}
